# Generated by Django 5.0.1 on 2024-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=None)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('data', models.DateTimeField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подработки',
                'verbose_name_plural': 'Подработки',
            },
        ),
    ]
